# OpenAI API Configuration
chat_model:
  model_name: "gpt-4o"
  temperature: 0.7
  max_tokens: 1024

# Embedding Model Configuration
embedding_model:
  model_name: "text-embedding-3-large"
  dimensions: 1536

vector_database:
  chroma:

chat_session_path: './chat_session/'